INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [13/Jun/2018 16:47:57] "GET /corporations/A0003650 HTTP/1.1" 500 -
INFO:werkzeug: * Detected change in '/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py', reloading
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [13/Jun/2018 16:48:36] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py', reloading
INFO:root:logging works
ERROR:flask.app:Exception on /corporations/A0003650 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 323, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 344, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Response' is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [13/Jun/2018 16:51:16] "GET /corporations/A0003650 HTTP/1.1" 500 -
INFO:werkzeug: * Detected change in '/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py', reloading
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [13/Jun/2018 16:52:11] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:werkzeug: * Detected change in '/Users/kial/work/backend/namex/colin-api/app/resources/ops.py', reloading
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 08:22:32] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 08:23:13] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 08:23:41] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 08:26:50] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 08:34:57] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 09:04:36] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:18:36] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:19:38] "GET /corporations/A0003650 HTTP/1.1" 200 -
ERROR:flask_oidc:ERROR: Unable to get token info
ERROR:flask_oidc:[Errno 60] Operation timed out
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:26:25] "GET /corporations/A0003650 HTTP/1.1" 401 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:28:37] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:29:30] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:29:38] "GET /corporations/A0003650 HTTP/1.1" 401 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:30:55] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:31:08] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:31:21] "GET /corporations/A0003650 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:31:21] "GET /corporations/A0003650 HTTP/1.1" 401 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 10:58:03] "GET /corporations/0008385 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/A0068045 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 116, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:26:53] "GET /api/v1/corporations/A0068045 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/A0068045 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 116, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:31:02] "GET /api/v1/corporations/A0068045 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/A0068045 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 117, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:34:17] "GET /api/v1/corporations/A0068045 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/A0068045 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 118, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:35:26] "GET /api/v1/corporations/A0068045 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/A0068045 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 118, in get
    print(5)
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:36:35] "GET /api/v1/corporations/A0068045 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/A0068045 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 119, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:36:56] "GET /api/v1/corporations/A0068045 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:40:15] "GET /api/v1/corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 115, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:44:41] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 116, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:45:26] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 118, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:45:56] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 118, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:46:34] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 118, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:47:15] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 119, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:48:18] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 119, in get
    except:
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:53:03] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:53:42] "GET /api/v1/corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 122, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:54:10] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 122, in get
    incorp_nob = 'Not Available'
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:55:08] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 124, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:55:31] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0018524 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 124, in get
    incorp_nr = incorp_nr_obj.fetchall()[0][1]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 11:57:32] "GET /api/v1/corporations/0018524 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:00:53] "GET /api/v1/corporations/0018524 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:01:59] "GET /api/v1/corporations/A0009146 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:02:38] "GET /api/v1/corporations/A0010642 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:03:13] "GET /api/v1/corporations/0009141 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:03:43] "GET /api/v1/corporations/0009162 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:04:16] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:11:31] "GET /api/v1/corporations/0022258 HTTP/1.1" 500 -
INFO:root:logging works
INFO:root:logging works
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:15:59] "GET /api/v1/corporations/0022258 HTTP/1.1" 500 -
INFO:root:logging works
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:17:14] "GET /api/v1/corporations/0022258 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:18:14] "GET /api/v1/corporations/0022258 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:19:24] "GET /api/v1/corporations/0022258 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:20:15] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0022258 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 110, in get
    incorp_addr_id_sql = '\'' + str(incorp_addr_id) + '\''
NameError: name 'incorp_addr_id' is not defined
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:26:35] "GET /api/v1/corporations/0022258 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:27:44] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:32:10] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:36:56] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:37:24] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:38:41] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:39:57] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:42:13] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
INFO:root:logging works
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:44:11] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0022259 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 109, in get
    incorp_rec_addr_id = incorp_addr_ids[1][0]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:44:53] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:45:38] "GET /api/v1/corporations/A0010642 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:46:08] "GET /api/v1/corporations/A0006152 HTTP/1.1" 200 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0022259 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 109, in get
    incorp_rec_addr_id = incorp_addr_ids[1][0]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:46:26] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0022259 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 109, in get
    incorp_rec_addr_id = incorp_addr_ids[1][0]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:47:13] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0022259 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 109, in get
    incorp_addr_ids = incorp_addr_id_obj.fetchall()
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:47:52] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0022259 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 111, in get
    incorp_rec_addr_id = incorp_addr_ids[1][0]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:48:01] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0022259 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 112, in get
    incorp_rec_addr_id = incorp_addr_ids[1][0]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:48:28] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0022259 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 113, in get
    incorp_rec_addr_id = incorp_addr_ids[1][0]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:49:26] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:53:40] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:54:24] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0022259 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 219, in get
    incorp_records_addr_test = incorp_records_addr_obj.fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:56:06] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
ERROR:flask.app:Exception on /api/v1/corporations/0022259 [GET]
Traceback (most recent call last):
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/kial/work/backend/namex/colin-api/venv/lib/python3.6/site-packages/flask_oidc/__init__.py", line 860, in decorated
    return view_func(*args, **kwargs)
  File "/Users/kial/work/backend/namex/colin-api/app/resources/corporations.py", line 220, in get
    incorp_records_addr_test = incorp_records_addr_obj.fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 12:57:17] "GET /api/v1/corporations/0022259 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:02:50] "GET /api/v1/corporations/0022259 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:04:10] "GET /api/v1/corporations/A0003650 HTTP/1.1" 500 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:05:25] "GET /api/v1/corporations/A0003650 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:08:14] "GET /api/v1/corporations/A0020251 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:08:51] "GET /api/v1/corporations/0022277 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:09:20] "GET /api/v1/corporations/0022297 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:09:47] "GET /api/v1/corporations/0022301 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:10:15] "GET /api/v1/corporations/0018477 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:10:43] "GET /api/v1/corporations/0018524 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:11:04] "GET /api/v1/corporations/0008385 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:11:26] "GET /api/v1/corporations/0009141 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:11:50] "GET /api/v1/corporations/0009162 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:12:18] "GET /api/v1/corporations/0011367 HTTP/1.1" 200 -
INFO:root:logging works
INFO:werkzeug:127.0.0.1 - - [14/Jun/2018 13:12:44] "GET /api/v1/corporations/0022258 HTTP/1.1" 200 -
